project/urls.py
from django.contrib import admin
from django.urls import path, include
from .routers import router
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('product', TemplateView.as_view(template_name='index.html')),
    path('', include(('users.urls', 'users'), namespace='users')),
]

users/urls.py
from django.urls import path
from .views import do_login, do_logout, create_user, update_user

urlpatterns = [
    path('', do_login, name='login'),
    path('logout', do_logout, name='logout'),
    path('register', create_user, name='register'),
    path('update/<int:id>/', update_user, name='update_user'),
]

product/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=250)
    category = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    description = models.TextField(blank=True)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User

class UserModelForm(forms.ModelForm):
    User._meta.get_field('first_name').blank = False
    User._meta.get_field('email').blank = False
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'maxlength':60}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'maxlength':100}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'maxlength':60}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'maxlength':60}),
        }
        labels = {
            'first_name': 'Name',
            'email': 'Email',
        }

    def save(self, commit=True):
        user = super(UserModelForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

product/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render, redirect
from users.forms import UserModelForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

def create_user(request):
    form = UserModelForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('/')
    return render(request, 'register.html', {'form': form})

@login_required
def update_user(request, id=1):
    id = request.user.id
    user = User.objects.get(id=id)
    form = UserModelForm(request.POST or None, instance=user)

    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request, 'users-form.html', {'form': form, 'user': user})

def do_login(request):
    form = UserModelForm(request.POST or None)
    error = ''

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            if user.is_active:
                try:
                    login(request, user)
                    return redirect('/product')
                except:
                    error = 'Internal error'
            else:
                error = 'Inactive user'
        else:
            error = 'Invalid username or password!'

    return render(request, 'login.html', {'form': form, 'error': error})

def do_logout(request):
    logout(request)
    return redirect('/')

product/templates/index.html
{% extends 'layouts/base.html' %}
{% block content %}
  <div id="starting">
      <h2>Products</h2>
      <button  type="button" class="btn btn-success" data-toggle="modal" data-target="#addProductModal"><i class="fa fa-plus"></i> Product</button>
      <div class="search-right">
        <form method="GET" action="">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" v-model="search_term" aria-label="Search">
          <button type="submit" class="btn btn-primary" v-on:click.prevent="getProducts()"><i class="fa fa-search"></i></button>
        </form>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Category</th>
            <th scope="col">Price</th>
            <th scope="col" class="text-center">Action</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="product in products">
            <th scope="row">${product.id}</th>
            <td>${product.name}</td>
            <td>${product.category}</td>
            <td>${product.price}</td>
            <td class="col-actions">
              <button class="btn btn-primary" v-on:click="getProduct(product.id)"><i class="fa fa-edit"></i> Edit</button>
              <button class="btn btn-danger" v-on:click="deleteProduct(product.id)"><i class="fa fa-trash"></i> Delete</button>
            </td>
          </tr>
        </tbody>
      </table>

      <!-- Add Product Modal -->
      <div class="modal fade" id="addProductModal" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h3 class="modal-title" id="modalTitle">Add Product</h3>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form v-on:submit.prevent="addProduct()">
            <div class="modal-body">
              <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" placeholder="Name" v-model="newProduct.name" required="required">
              </div>
              <div class="form-group">
                <label for="category">Category</label>
                <input type="text" class="form-control" id="category" placeholder="Category" v-model="newProduct.category" required="required">
              </div>
              <div class="form-group">
                <label for="price">Price</label>
                <input type="text" class="form-control" id="price" placeholder="Price" v-model="newProduct.price" required="required">
              </div>
              <div class="form-group">
                <label for="description">Description</label>
                <textarea class="form-control" id="description" placeholder="Description" v-model="newProduct.description" rows="3"></textarea>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
              <button type="submit" class="btn btn-success"><i class="fa fa-hdd-o"></i> Save</button>
            </div>
            </form>
          </div>
        </div>
        <div class="loading" v-if="loading===true">Loading&#8230;</div>
      </div>
      <!-- End of add article modal -->

      <!-- Edit Product Modal -->
      <div class="modal fade" id="editProductModal" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h3 class="modal-title" id="modalTitle">Edit Product</h3>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form v-on:submit.prevent="updateProduct()">
            <div class="modal-body">
              <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" placeholder="Name" v-model="currentProduct.name" required="required">
              </div>
              <div class="form-group">
                <label for="category">Category</label>
                <input type="text" class="form-control" id="category" placeholder="Category" v-model="currentProduct.category" required="required">
              </div>
              <div class="form-group">
                <label for="price">Price</label>
                <input type="text" class="form-control" id="price" placeholder="Price" v-model="currentProduct.price" required="required">
              </div>
              <div class="form-group">
                <label for="description">Description</label>
                <textarea class="form-control" id="description" placeholder="Description" v-model="currentProduct.description" rows="3"></textarea>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
              <button type="submit" class="btn btn-success"><i class="fa fa-hdd-o"></i> Save</button>
            </div>
            </form>
          </div>
        </div>
        <div class="loading" v-if="loading===true">Loading&#8230;</div>
      </div>
      <!-- End of edit article modal -->
    <div class="loading" v-if="loading===true">Loading&#8230;</div>
  </div>
{% endblock %}

templates/layouts/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/pagination.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>Django VueJS</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container-header">
        <div class="navbar-header">
          <!-- Collapsed Hamburger -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <!-- Branding Image -->
          <a class="navbar-brand" href="/product">
            <strong>Django VueJS</strong>
          </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
          <!-- Left Side Of Navbar -->
          <!-- <ul class="nav navbar-nav">
            <li class="nav-item">Link1</li>
            <li class="nav-item">Link2</li>
            <li class="nav-item">Link3</li>
          </ul> -->

          <!-- Right Side Of Navbar -->
          <ul class="nav navbar-nav navbar-right">
            <!-- Authentication Links -->
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    <img src="{% static 'img/avatar-placeholder.svg' %}" alt="" width="30" class="img-circle">
                    {{ user.get_username }} <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'users:update_user' 1 %}">Profile</a></li>
                    <li><a href="{% url 'users:logout' %}">Logout</a></li>
                </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vue.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vue-resource.js' %}"></script>

    <script type="text/javascript">
        Vue.http.headers.common['X-CSRFToken'] = "{{ csrf_token }}";
    </script>
    <script type="text/javascript" src="{% static 'js/app.js' %}"></script>

</body>
</html>

templates/layouts/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>Django VueJS</title>
</head>
<body class="page-login">
    <div class="container-login">
        {% block content %}
        {% endblock %}
    </div>

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

users/templates/login.html
{% extends 'layouts/login.html' %}
{% load bootstrap %}
{% block content %}
  <form action="{% url 'users:login' %}" method="POST">
    {% csrf_token %}
    <div class="panel panel-default">
    	<div class="panel-body box-login">
        <h3 class="title-login">Sign in</h3>
        <div class="form-group">
          <label for="username" class="sr-only">Username</label>
          <span class="fa fa-user"></span>
          <input type="text" name="username" class="form-control input-login" placeholder="Username" required autofocus>
        </div>
        <div class="form-group">
          <label for="password" class="sr-only">Password</label>
          <span class="fa fa-lock"></span>
          <input type="password" name="password" class="form-control input-login" placeholder="Password" required>
        </div>
        <div class="form-group">
          <button class="btn btn-lg btn-success btn-block" type="submit">Login</button>
        </div>
        <a href="{% url 'users:register' %}" class="link-register">Create an account</a>
    		{% if error %}
    			<div class="alert alert-danger">{{error}}</div>
    		{% endif %}
      </div>
    </div>
    <div class="text-center">
      <strong>Test Login:</strong><br><br>
      Username: admin<br>
      Password: admin<br>
    </div>
  </form>
{% endblock %}

users/templates/register.html
{% extends 'layouts/login.html' %}
{% load bootstrap %}
{% block content %}
  <div class="panel panel-default">
  	<div class="panel-body">
			<h3 class="title-login">Sign Up</h3>
      <form method="POST">
          {% csrf_token %}
          {{ form|bootstrap }}
          <a href="/" class="btn btn-outline-secondary"><i class="fa fa-arrow-left"></i> Back</a>
  				<button type="submit" class="btn btn-success"><i class="fa fa-hdd-o"></i> Save</button>
      </form>
    </div>
  </div>
{% endblock %}

users/templates/users-form.html
{% extends 'layouts/base.html' %}
{% load bootstrap %}
{% block content %}
	<h2>Profile</h2>

  <div class="panel panel-default">
  	<div class="panel-body">
  		<div class="container-form col-sm-5">
        <form method="POST" novalidate>
            {% csrf_token %}
            {{ form|bootstrap }}
            <a href="/product" class="btn btn-outline-secondary"><i class="fa fa-arrow-left"></i> Back</a>
    				<button type="submit" class="btn btn-success"><i class="fa fa-hdd-o"></i> Save</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}